package com.photographercamera.core.photon.hdr

import android.graphics.Bitmap
import android.graphics.Gainmap

enum class SourceKind {
    RAW,
    SDR_BITMAP,
}

enum class HdrBufferEncoding {
    LINEAR_SRGB,
}

enum class LuminanceGainMapEncoding {
    LINEAR_RATIO,
}

data class LuminanceGainMap(
    val bitmap: Bitmap,
    val encoding: LuminanceGainMapEncoding,
)

data class HdrBuffer(
    val bitmap: Bitmap,
    val encoding: HdrBufferEncoding,
    val description: String? = null,
)

data class GainmapSourceSet(
    val sdrBase: Bitmap,
    /** Pixel-aligned sidecar generated by the LUT stack from its before/after linear luminance. */
    val lutLuminanceGainMap: LuminanceGainMap? = null,
    val hdrReference: HdrBuffer? = null,
    val sourceKind: SourceKind,
    val confidence: Float = 1.0f,
    val displayHdrSdrRatio: Float = 0f,
)

data class GainmapResult(
    val gainmap: Gainmap,
    val sourceKind: SourceKind,
    val confidence: Float = 1.0f,
)
